package main

import (
	"bytes"
	_ "embed"
	"fmt"

	v776 "cyu-core-26.2/internal/protocol/java/v776"
	"cyu-core-26.2/internal/registry"
	"cyu-core-26.2/internal/vanilla/datagen"
)

const minecraftDataVersion26_2 = 4903

// The checked-in data is generated by .github/workflows/vanilla-data.yml from
// an official Minecraft 26.2 server. It is kept as structured JSON in the
// repository for reviewability, then embedded so a CyuCore binary has no
// runtime dependency on its working directory.
//
//go:embed data/26.2/registry-set.json
var vanillaRegistryDataset26_2 []byte

//go:embed data/26.2/manifest.json
var vanillaRegistryManifest26_2 []byte

type vanillaConfiguration struct {
	registryData [][]byte
	updateTags   []byte
}

func loadVanillaConfiguration26_2() (*vanillaConfiguration, error) {
	expected := datagen.Version{
		Minecraft: "26.2",
		Protocol:  int(v776.ProtocolVersion),
		Data:      minecraftDataVersion26_2,
	}
	manifest, err := datagen.DecodeManifest(bytes.NewReader(vanillaRegistryManifest26_2), expected)
	if err != nil {
		return nil, fmt.Errorf("vanilla data manifest: %w", err)
	}
	if manifest.Source.Kind != datagen.MojangServerCapture {
		return nil, fmt.Errorf("vanilla data manifest: source kind %q is not an authoritative server capture", manifest.Source.Kind)
	}

	set, err := registry.DecodeDataset(bytes.NewReader(vanillaRegistryDataset26_2))
	if err != nil {
		return nil, fmt.Errorf("vanilla registry dataset: %w", err)
	}
	if err := v776.ValidateConfigurationSet(set); err != nil {
		return nil, fmt.Errorf("vanilla registry dataset: %w", err)
	}

	registries, err := v776.RegistryDataRegistries(set)
	if err != nil {
		return nil, fmt.Errorf("vanilla registry dataset: %w", err)
	}
	registryData := make([][]byte, len(registries))
	for i, reg := range registries {
		payload, err := v776.EncodeRegistryData(reg)
		if err != nil {
			return nil, fmt.Errorf("encode RegistryData %s: %w", reg.Key(), err)
		}
		registryData[i] = payload
	}
	updateTags, err := v776.EncodeUpdateTags(set)
	if err != nil {
		return nil, fmt.Errorf("encode UpdateTags: %w", err)
	}

	return &vanillaConfiguration{
		registryData: registryData,
		updateTags:   updateTags,
	}, nil
}
